import {StyleSheet} from 'react-native';
import {color, globalStyle} from '../../consts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: globalStyle['padding-horizontal'],
    backgroundColor: color['background-color'],
  },
  extraTxt: {
    fontSize: globalStyle['fontsize-large'],
    fontFamily: globalStyle['fontfamily-medium'],
    color: color['black-color'],
    marginTop: globalStyle['space-top'] + 15,
    marginBottom: globalStyle['space-bottom'] + 3,
  },
  voucherInput: {
    width: '100%',
    height: globalStyle['height'] + 5,
    backgroundColor: color['white-color'],
    borderRadius: globalStyle['border-radius'],
    borderWidth: 1,
    borderColor: 'lightgray',
    fontSize: globalStyle['fontsize-medium'],
    fontFamily: globalStyle['fontfamily-medium'],
    paddingLeft: globalStyle['space-left'] + 10,
    elevation: 1,
  },
  voucherbtn: {
    height: globalStyle['height'] + 5,
    width: '100%',
    borderRadius: globalStyle['border-radius'],
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: color['primary-color'],
    marginVertical: globalStyle['margin-vertical'],
    elevation: 1,
  },
  voucherBtnTxt: {
    fontFamily: globalStyle['fontfamily-medium'],
    fontSize: globalStyle['fontsize-large'],
    color: color['white-color'],
  },
  billContainer: {
    width: '100%',
    backgroundColor: color['white-color'],
    borderRadius: globalStyle['border-radius'],
    borderWidth: 1,
    borderColor: 'lightgray',
    padding: 10,
  },
  billAmountView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: globalStyle['margin-vertical'],
  },
  billAmountParentTxt: {
    fontSize: globalStyle['fontsize-medium'] + 1,
    fontFamily: globalStyle['fontfamily-medium'],
    color: color['black-color'],
  },
  billAmountlabel: {
    fontSize: globalStyle['fontsize-medium'] + 1,
    fontFamily: globalStyle['fontfamily-medium'],
    color: color['black-color'],
  },
  billAmountPriceTxt: {
    fontSize: globalStyle['fontsize-medium'] + 2,
    fontFamily: globalStyle['fontfamily-bold'],
    color: color['black-color'],
  },
  orderbtn: {
    height: globalStyle['height'] + 5,
    width: '100%',
    borderRadius: globalStyle['border-radius'],
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: color['primary-color'],
    marginVertical: globalStyle['margin-vertical'],
    elevation: 1,
  },
  orderBtnTxt: {
    fontFamily: globalStyle['fontfamily-medium'],
    fontSize: globalStyle['fontsize-large'],
    color: color['white-color'],
  },
  addressContainer: {
    height: globalStyle['height'],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: color['white-color'],
    paddingHorizontal: globalStyle['padding-horizontal'],
    borderRadius: globalStyle['border-radius'],
    borderWidth: 1,
    borderColor: 'lightgray',
    elevation: 1,
  },
  addressTxt: {
    fontSize: globalStyle['fontsize-medium'],
    fontFamily: globalStyle['fontfamily-medium'],
    color: color['black-color'],
  },
  paymentContainer: {
    height: globalStyle['height'],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: color['white-color'],
    paddingHorizontal: globalStyle['padding-horizontal'],
    borderRadius: globalStyle['border-radius'],
    borderWidth: 1,
    borderColor: 'lightgray',
    elevation: 1,
  },
  paymentTxt: {
    fontSize: globalStyle['fontsize-medium'],
    fontFamily: globalStyle['fontfamily-medium'],
    color: color['black-color'],
  },
});
